name: flutter_course_shop_ui
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_rating_bar: ^3.2.0+1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  line_icons: ^0.2.0
  google_fonts: ^1.1.0
  flutter_svg: 0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  #  fonts:
  #    - family: yekan
  #      fonts:
  #        - asset: fonts/IRANYekanMobileRegular.ttf
  #          weight: 500
  #        - asset: fonts/IRANYekanMobileBold.ttf
  #          weight: 600
  #        - asset: fonts/IRANYekanMobileLight.ttf
  #          weight: 400
  #        - asset: fonts/lalezar.ttf
  #          weight: 400

  uses-material-design: true
  assets:
    - assets/

